version: '3.8'
services:
db:
image: postgres:15
environment:
POSTGRES_DB: ctfd
POSTGRES_USER: ctfd
POSTGRES_PASSWORD: ctfd
volumes:
- ./data/postgres:/var/lib/postgresql/data


redis:
image: redis:6
volumes:
- ./data/redis:/data


ctfd:
build: .
depends_on:
- db
- redis
ports:
- "8000:8000"
environment:
SECRET_KEY: "changeme"
DATABASE_URL: "postgresql+psycopg2://ctfd:ctfd@db:5432/ctfd"
REDIS_URL: "redis://redis:6379/0"
volumes:
- ./uploads:/var/uploads
command: gunicorn "CTFd:create_app()" -b 0.0.0.0:8000 -w 9 --threads 4 --timeout 90
