services:
  - type: web
    name: ctfd
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install psycopg2-binary gunicorn
    startCommand: gunicorn "CTFd:create_app()" -b 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ctfd-db
          property: connectionString

databases:
  - name: ctfd-db
    plan: free
